### ISSUE TITLE
adb-send-string

### ISSUE THREAD

**Issue by lexgorbunov** [matthijskooijman/scripts#1]
$ adbst "Тест"

java.lang.NullPointerException: Attempt to get length of null array
	at com.android.commands.input.Input$InputText.sendText(Input.java:168)
	at com.android.commands.input.Input$InputText.run(Input.java:140)
	at com.android.commands.input.Input.onRun(Input.java:107)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
	at com.android.commands.input.Input.main(Input.java:71)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)

**Comment by matthijskooijman** [comment]
Hm, I'm afraid this might be a limitation of adb... Also, when I try this, I just get:

```
$  adb-send-string "Тест"
Killed 
```

Did you do anything special to get that backtrace?

I also stopped using this particular script, so I think I'm going to remove it. Instead, I now use https://github.com/gcb/AdbPaste which is a bit more complete. However, it does seem to suffer from the same issue (The core of that script is the same).

Since I'm removing this script here, I'm going to close this issue. Maybe you could also consider switching to AdbPaste and open an issue there for further discussion?
